name = "Matroid"
keywords = ["math"]
defaultTargets = ["Matroid"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
pp.proofs.withType = false
linter.docPrime = false
linter.style.longLine = true
linter.unusedSimpArgs = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Canonical"
scope = "chasenorman"

[[lean_lib]]
name = "Matroid"
