name = "Matroid"
keywords = ["math"]
defaultTargets = ["Matroid"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
pp.proofs.withType = false
linter.docPrime = false
linter.style.longLine = true
linter.unusedSimpArgs = true

[[require]]
name = "loogle"
git = "https://github.com/nomeata/loogle"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Matroid"
